In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
sns.set_style('darkgrid')
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv('Train.csv')
train_data.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
train_data['area_type'].value_counts()

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64

In [4]:
# train_data['availability'].value_counts()

In [5]:
# train_data['location'].value_counts()

In [6]:
# train_data['size'].value_counts()

In [7]:
train_data.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [8]:
# train_data['society'].value_counts()
train_data.shape

(13320, 9)

In [9]:
train_data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [10]:
train_data['society'].fillna("MissingSociety",inplace=True)

In [11]:
train_data.isnull().sum()

area_type         0
availability      0
location          1
size             16
society           0
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [12]:
train_data.dropna(subset=['location'],inplace=True)

In [13]:
train_data['bath'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['bath']
train_data['balcony'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['balcony']

In [14]:
train_data.isnull().sum()

area_type        0
availability     0
location         0
size            16
society          0
total_sqft       0
bath             1
balcony         45
price            0
dtype: int64

In [15]:
train_data['bath'].fillna(train_data['bath'].median(),inplace=True)
train_data['balcony'].fillna(train_data['balcony'].median(),inplace=True)

In [16]:
train_data['size']=train_data['size'].apply(lambda x:str(x).split(" ")[0]).astype(float)

In [17]:
train_data['size'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['size']

In [18]:
train_data.dropna(subset=['size'],inplace=True)

In [19]:
# train_data.isnull().sum()
train_data.shape

(13318, 9)

In [20]:
train_data.head(3)

area_type   availability                  location  size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II   2.0   
1            Plot  Area  Ready To Move          Chikka Tirupathi   4.0   
2        Built-up  Area  Ready To Move               Uttarahalli   3.0   

          society total_sqft  bath  balcony   price  
0         Coomee        1056   2.0      1.0   39.07  
1         Theanmp       2600   5.0      3.0  120.00  
2  MissingSociety       1440   2.0      3.0   62.00

In [21]:
train_data.drop('availability',1,inplace=True)

In [22]:
train_data.head(3)

area_type                  location  size         society  \
0  Super built-up  Area  Electronic City Phase II   2.0         Coomee    
1            Plot  Area          Chikka Tirupathi   4.0         Theanmp   
2        Built-up  Area               Uttarahalli   3.0  MissingSociety   

  total_sqft  bath  balcony   price  
0       1056   2.0      1.0   39.07  
1       2600   5.0      3.0  120.00  
2       1440   2.0      3.0   62.00

In [23]:
train_data['Location']=train_data['location']+" "+train_data['society']

In [24]:
areatype=pd.get_dummies(train_data[['area_type']],drop_first=True)

In [25]:
areatype.head()

area_type_Carpet  Area  area_type_Plot  Area  \
0                       0                     0   
1                       0                     1   
2                       0                     0   
3                       0                     0   
4                       0                     0   

   area_type_Super built-up  Area  
0                               1  
1                               0  
2                               0  
3                               1  
4                               1

In [26]:
df=pd.concat([train_data,areatype],axis=1)

In [27]:
df.drop('area_type',1,inplace=True)

In [28]:
df.drop(['location','society'],1,inplace=True)

In [29]:
df.head()

size total_sqft  bath  balcony   price                          Location  \
0   2.0       1056   2.0      1.0   39.07  Electronic City Phase II Coomee    
1   4.0       2600   5.0      3.0  120.00          Chikka Tirupathi Theanmp   
2   3.0       1440   2.0      3.0   62.00        Uttarahalli MissingSociety   
3   3.0       1521   3.0      1.0   95.00        Lingadheeranahalli Soiewre   
4   2.0       1200   2.0      1.0   51.00           Kothanur MissingSociety   

   area_type_Carpet  Area  area_type_Plot  Area  \
0                       0                     0   
1                       0                     1   
2                       0                     0   
3                       0                     0   
4                       0                     0   

   area_type_Super built-up  Area  
0                               1  
1                               0  
2                               0  
3                               1  
4                               1

In [54]:
df.dtypes

size                              float64
total_sqft                         object
bath                              float64
balcony                           float64
price                             float64
Location                           object
area_type_Carpet  Area              uint8
area_type_Plot  Area                uint8
area_type_Super built-up  Area      uint8
dtype: object

In [60]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [62]:
# df['total_sqft'].value_counts()

1200                 843
1100                 221
1500                 205
2400                 196
600                  180
1000                 172
1350                 133
1050                 123
1300                 117
1250                 114
900                  112
1400                 108
1800                 104
1150                 101
1600                 100
1140                  91
2000                  83
1450                  70
1650                  69
800                   67
1075                  66
3000                  66
1020                  63
2500                  62
1125                  60
1160                  60
1550                  60
950                   59
1180                  58
1700                  58
1260                  57
1255                  56
1220                  55
1080                  55
1070                  53
750                   52
700                   52
1225                  48
1175                  48
4000                  48


In [63]:
def preprocess_total_sqft(my_list):
    if len(my_list) == 1:
        
        try:
            return float(my_list[0])
        except:
            strings = ['Sq. Meter', 'Sq. Yards', 'Perch', 'Acres', 'Cents', 'Guntha', 'Grounds']
            split_list = re.split('(\d*.*\d)', my_list[0])[1:]
            area = float(split_list[0])
            type_of_area = split_list[1]
            
            if type_of_area == 'Sq. Meter':
                area_in_sqft = area * 10.7639
            elif type_of_area == 'Sq. Yards':
                area_in_sqft = area * 9.0
            elif type_of_area == 'Perch':
                area_in_sqft = area * 272.25
            elif type_of_area == 'Acres':
                area_in_sqft = area * 43560.0
            elif type_of_area == 'Cents':
                area_in_sqft = area * 435.61545
            elif type_of_area == 'Guntha':
                area_in_sqft = area * 1089.0
            elif type_of_area == 'Grounds':
                area_in_sqft = area * 2400.0
            return float(area_in_sqft)
        
    else:
        return (float(my_list[0]) + float(my_list[1]))/2.0

In [65]:
df['total_sqft'] = df.total_sqft.str.split('-').apply(preprocess_total_sqft)

In [66]:
df_num=df.drop(['Location','price'],1)

In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [68]:
df_num = scaler.fit_transform(df_num,1)
df_num

array([[2.38095238e-02, 8.07316198e-04, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [7.14285714e-02, 1.98882919e-03, 1.02564103e-01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.76190476e-02, 1.10116399e-03, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.38095238e-02, 8.72360631e-04, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.14285714e-02, 3.58739179e-03, 7.69230769e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 4.20110514e-04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [69]:
df_txt=df['Location']

In [70]:
# df_txt['Location'] = df_txt[df_txt.columns[0:]].apply(
#     lambda x: ','.join(x.dropna().astype(str)),
#     axis=1)

# df_txt.main.head(3)

In [71]:
# df_txt.head(20)

In [72]:
y=df['price']

In [73]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\welcome\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
vector = TfidfVectorizer(max_features = 3000, min_df = 1, max_df = 0.6,ngram_range = (1,2))
X_text = vector.fit_transform(df_txt).toarray()

In [76]:
X_text

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
X = np.concatenate((X_text,df_num),axis = 1)
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
X.shape

(13318, 3007)

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 42)

In [80]:
from sklearn.ensemble import RandomForestRegressor

In [81]:
regr = RandomForestRegressor(n_jobs = 4, random_state = 42, n_estimators = 100, verbose = 1, max_features = 'auto')

In [82]:
regr.fit(X_train, y_train)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:  2.1min
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:  4.4min finished


RandomForestRegressor(n_jobs=4, random_state=42, verbose=1)

In [83]:
regr.score(X_train,y_train)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.6s finished


0.9497157733648984

In [85]:
import numpy as np
from sklearn import metrics

pred1 = regr.predict(X_test) 
rmse = np.sqrt(metrics.mean_squared_error(y_test, pred1)) 
print("RMSE : % f" %(rmse)) 

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


RMSE :  61.891879


In [86]:
metrics.r2_score(y_test, pred1)

0.7950209182837843